### ISSUE TITLE
[BUG] - Broken links in Wiki for iiqka controllers

### ISSUE THREAD

**Issue by pucciland95** [kroshu/kuka_drivers#142]
### Description

In the wiki of [iiQKA_EAC](https://github.com/pucciland95/kuka_drivers_polimi/wiki/iiQKA_EAC) there are 3 broken links that should send the reader to the configuration files of:
- joint_trajectory_controller
- joint_group_impedance_controller
- effort_controller

If the documentation is open locally, this error does not happen since the path to the file is relative to the file itself (iiQKA_EAC.md). However, such a relative path is broken if opened from the Wiki in Git Hub.

Unfortunately, Git Hub does not allow pull requests limited to the Wiki. Therefore, I made a fork of the repo at the following [link](https://github.com/pucciland95/kuka_drivers_polimi/wiki/iiQKA_EAC), where I fixed the path of the three files. 

I hope it helps,

Niccolo

### KUKA robot OS version

None

### KUKA external interface version

None

### Affected robot model(s)

None

### Setup

```bash
None
```

### Reproduction steps

```bash
None
```

**Comment by Svastits** [comment]
Thanks, I have fixed the relative links in all wiki md files, PR will be merged soon :)
