### ISSUE TITLE
Add rviz sphere to driver launch files

### ISSUE THREAD

**Issue by Svastits** [kroshu/kuka_drivers#182]
The fix in [this PR](https://github.com/kroshu/kuka_robot_descriptions/pull/61) should be merged to the driver launch files too

**Comment by prasuchit** [comment]
@Svastits, I'm currently on Jazzy and I still don't see the Moveit interactive planning marker. Any update on this pull request?

**Comment by Svastits** [comment]
The fixes have not yet been applied to the driver launch files, only for the moveit ones with fake hardware
We will do it soon :)
