### ISSUE TITLE
[BUG] - A namespace collision has occurred with plugin factory for class

### ISSUE THREAD

**Issue by terkaa** [kroshu/kuka_drivers#183]
### Description

I am not quite sure what happened yesterday, suddenly the robot links lost transform to world? Related to ROS updates?  I made a fresh install of this ROS workspace but it did not solve the issue. Below is a launch log:

[move_group-6] You can start planning now!
[move_group-6] 
[spawner-5] [INFO] [1725184816.210178691] [spawner_joint_trajectory_controller]: Set controller params file to "/home/tero/pera/install/kuka_resources/share/kuka_resources/config/fake_hardware_config_6_axis.yaml" for joint_trajectory_controller
[ros2_control_node-1] [INFO] [1725184816.210687520] [controller_manager]: Loading controller 'joint_trajectory_controller'
[ros2_control_node-1] [WARN] [1725184816.217007642] [joint_trajectory_controller]: [Deprecated]: "allow_nonzero_velocity_at_trajectory_end" is set to true. The default behavior will change to false.
[spawner-5] [INFO] [1725184816.225622912] [spawner_joint_trajectory_controller]: Loaded joint_trajectory_controller
[ros2_control_node-1] [INFO] [1725184816.226151655] [controller_manager]: Configuring controller 'joint_trajectory_controller'
[ros2_control_node-1] [INFO] [1725184816.226348479] [joint_trajectory_controller]: No specific joint names are used for command interfaces. Using 'joints' parameter.
[ros2_control_node-1] [INFO] [1725184816.226380130] [joint_trajectory_controller]: Command interfaces are [position] and state interfaces are [position].
[ros2_control_node-1] [INFO] [1725184816.226407164] [joint_trajectory_controller]: Using 'splines' interpolation method.
[ros2_control_node-1] [INFO] [1725184816.227169671] [joint_trajectory_controller]: Controller state will be published at 50.00 Hz.
[ros2_control_node-1] [INFO] [1725184816.228963547] [joint_trajectory_controller]: Action status changes will be monitored at 20.00 Hz.
[spawner-4] Traceback (most recent call last):
[spawner-4]   File "/opt/ros/humble/lib/controller_manager/spawner", line 33, in <module>
[spawner-4]     sys.exit(load_entry_point('controller-manager==2.43.0', 'console_scripts', 'spawner')())
[spawner-4]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/controller_manager/spawner.py", line 212, in main
[spawner-4]     else get_parameter_from_param_file(
[spawner-4]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/controller_manager/spawner.py", line 85, in get_parameter_from_param_file
[spawner-4]     with open(parameter_file) as f:
[spawner-4] FileNotFoundError: [Errno 2] No such file or directory: ''
[spawner-5] [INFO] [1725184816.285631986] [spawner_joint_trajectory_controller]: Configured and activated joint_trajectory_controller
[ERROR] [spawner-4]: process has died [pid 15314, exit code 1, cmd '/opt/ros/humble/lib/controller_manager/spawner joint_state_broadcaster -c /controller_manager -p --ros-args'].
[rviz2-3] Warning: class_loader.impl: SEVERE WARNING!!! A namespace collision has occurred with plugin factory for class rviz_default_plugins::displays::InteractiveMarkerDisplay. New factory will OVERWRITE existing one. This situation occurs when libraries containing plugins are directly linked against an executable (the one running right now generating this message). Please separate plugins out into their own library or just don't link against the library and use either class_loader::ClassLoader/MultiLibraryClassLoader to open.
[rviz2-3]          at line 253 in /opt/ros/humble/include/class_loader/class_loader/class_loader_core.hpp
[INFO] [spawner-5]: process has finished cleanly [pid 15316]
[rviz2-3] [ERROR] [1725184819.528908219] [moveit_ros_visualization.motion_planning_frame]: Action server: /recognize_objects not available

![Screenshot from 2024-09-01 13-01-16](https://github.com/user-attachments/assets/13546857-35a8-442b-8f9e-641897be72be)

### KUKA robot OS

KSS

### KUKA robot OS version

KSS 8.6

### KUKA external interface version

RSI 4.1.3

### Affected robot model(s)

KR10_R1100_2

### Setup

```bash
Ubuntu 22.04
Fresh install
```

### Reproduction steps

```bash
Install ROS Humble
Clone the repository
Colcon Build
```

**Comment by Svastits** [comment]
It seems something changed in the core ROS2 that effects parametrization
This change only seems to break the moveit launch files with fake hardware, so the fix was done in the kuka_robot_desriptions repo in [this PR](https://github.com/kroshu/kuka_robot_descriptions/pull/63)

Please check if it has indeed resolved the issue on your side too :)
