### ISSUE TITLE
[BUG] - Unable to connect to the real robot - KUKA lbr iisy 3

### ISSUE THREAD

**Issue by prasuchit** [kroshu/kuka_drivers#188]
### Description

Hi @Svastits , I successfuly moved to Jazzy and installed all the prerequisites correctly. I was able to successfuly install an RT kernel for my linux kernel version and when I use uname -a I see:  Linux foraker 6.8.0-rt8 #1 SMP PREEMPT_RT Wed Oct  9 18:34:40 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux

I cloned the master branch kuka_drivers and kuka_descriptions and compiled everything successfuly. Now when I run ros2 launch iiqka_moveit_example moveit_planning_example.launch.py, and then do ros2 lifecycle set robot_manager configure, I see: Transition successful. On the driver terminal I see:

[control_node-1] [INFO] [1728516737.197882920] [control_mode_handler]: Control mode changed to 1
[control_node-1] [INFO] [1728516737.198031465] [resource_manager]: 'configure' hardware 'lbr_iisy3_r760' 
[control_node-1] [INFO] [1728516737.227578052] [KukaEACHardwareInterface]: Set QoS profile with 2 consequent and 1 packet losses allowed in 5000 milliseconds
[control_node-1] [INFO] [1728516737.227661239] [resource_manager]: Successful 'configure' of hardware 'lbr_iisy3_r760'
[control_node-1] [INFO] [1728516737.228362033] [controller_manager]: Activating controllers: [ control_mode_handler event_broadcaster ]
[control_node-1] [INFO] [1728516737.228462057] [controller_manager]: Switch controller timeout is set to 0, using default 1s!

However, when I do ros2 lifecycle set robot_manager activate, transition fails and on the driver terminal I see:

[robot_manager_node-2] [INFO] [1728516737.251241682] [robot_manager]: Activated control mode handler and event broadcaster
[control_node-1] [INFO] [1728516747.725502542] [resource_manager]: 'activate' hardware 'lbr_iisy3_r760' 
[ERROR] [control_node-1]: process has died [pid 4166, exit code -9, cmd '/home/psuresh/colcon_ws/install/kuka_drivers_core/lib/kuka_drivers_core/control_node --ros-args -r __ns:=/ --params-file /tmp/launch_params_2ook87ef --params-file /home/psuresh/colcon_ws/install/kuka_iiqka_eac_driver/share/kuka_iiqka_eac_driver/config/ros2_controller_config.yaml --params-file /tmp/launch_params_4hd4wrqe'].
[robot_manager_node-2] [ERROR] [1728516752.725455491] [robot_manager]: Could not activate hardware interface

I've also run updates on the SmartPad to make sure everything is up to date. I'm not sure what is causing this. Kindly help!

### KUKA robot OS version

iiQKA.OS 1.2.13

### KUKA external interface version

iiQKA 1.0.3

### Affected robot model(s)

KUKA lbr iisy 3

### Setup

```bash
N/A
```

### Reproduction steps

```bash
N/A
```

**Comment by Svastits** [comment]
Hi, could you check if this issue also occurs with fake hardware?
