### ISSUE TITLE
[BUG] - can not move the robot

### ISSUE THREAD

**Issue by liudedong1130** [kroshu/kuka_drivers#203]
### Description

I imported the urdf file of kr60 from another [repositoryI](https://github.com/simonschmeisser/kuka_experimental/tree/hydro-devel/kuka_kr60_support). And I set the rsi as tutorial in the wiki. 
Then, I executed the following commands to connect:
`ros2 launch kuka_kss_rsi_driver startup_with_rviz.launch.py client_ip:=192.168.1.40`
`ros2 lifecycle set robot_manager configure`
`ros2 lifecycle set robot_manager activate`
After that, I can successfully see the real-time status of the robot in rviz, and I can see the joint position by `ros2 topic echo /joint_states` in real time.
However, when i want to move the robot by `ros2 launch iiqka_moveit_example launch_trajectory_publisher.launch`, the robot doesn't move.
The question is as the wiki say, **"On successful activation the brakes of the robot will be released and external control is started."**, but i can't see anything to know about whether i have activate successfully include the brake and external control.
But i can get the status on ROS.

### KUKA robot OS

KSS

### KUKA robot OS version

KSS8.6

### KUKA external interface version

RSI4.0

### Affected robot model(s)

KR60

### Setup

```bash
I didn't modify any file, except the robot descriptions for kr60
```

### Reproduction steps

```bash
1.install by https://github.com/kroshu/kuka_drivers#installation
2.copy mesh file from https://github.com/simonschmeisser/kuka_experimental/tree/hydro-devel/kuka_kr60_support/meshes/kr60ha
3.copy kr6_r700_sixx.urdf.xacro as a template for kr60, and modify the parameters according to https://github.com/simonschmeisser/kuka_experimental/tree/hydro-devel/kuka_kr60_support/urdf
4.run:
ros2 launch kuka_kss_rsi_driver startup_with_rviz.launch.py client_ip:=192.168.1.40
ros2 lifecycle set robot_manager configure
ros2 lifecycle set robot_manager activate
5.run ros_rsi.src on the teach pad
6.run "ros2 launch iiqka_moveit_example launch_trajectory_publisher.launch"
```

### Logs

```bash
The log after run "ros2 launch kuka_kss_rsi_driver startup_with_rviz.launch.py client_ip:=192.168.1.40":
[INFO] [launch]: All log files can be found below /home/liu/.ros/log/2024-12-06-16-01-05-327109-liu-virtual-machine-112454
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [control_node-1]: process started with pid [112467]
[INFO] [robot_manager_node-2]: process started with pid [112469]
[INFO] [robot_state_publisher-3]: process started with pid [112471]
[INFO] [spawner-4]: process started with pid [112473]
[INFO] [spawner-5]: process started with pid [112475]
[INFO] [rviz2-6]: process started with pid [112477]
[robot_state_publisher-3] [INFO] [1733472065.802799466] [robot_state_publisher]: got segment base
[robot_state_publisher-3] [INFO] [1733472065.803017627] [robot_state_publisher]: got segment base_link
[robot_state_publisher-3] [INFO] [1733472065.803027125] [robot_state_publisher]: got segment flange
[robot_state_publisher-3] [INFO] [1733472065.803031954] [robot_state_publisher]: got segment link_1
[robot_state_publisher-3] [INFO] [1733472065.803036352] [robot_state_publisher]: got segment link_2
[robot_state_publisher-3] [INFO] [1733472065.803040901] [robot_state_publisher]: got segment link_3
[robot_state_publisher-3] [INFO] [1733472065.803045329] [robot_state_publisher]: got segment link_4
[robot_state_publisher-3] [INFO] [1733472065.803049767] [robot_state_publisher]: got segment link_5
[robot_state_publisher-3] [INFO] [1733472065.803054336] [robot_state_publisher]: got segment link_6
[robot_state_publisher-3] [INFO] [1733472065.803058694] [robot_state_publisher]: got segment tool0
[robot_state_publisher-3] [INFO] [1733472065.803063093] [robot_state_publisher]: got segment world
[rviz2-6] Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
[control_node-1] [WARN] [1733472065.829108329] [controller_manager]: [Deprecated] Passing the robot description parameter directly to the control_manager node is deprecated. Use '~/robot_description' topic from 'robot_state_publisher' instead.
[control_node-1] [INFO] [1733472065.829595967] [resource_manager]: Loading hardware 'kr60' 
[control_node-1] [INFO] [1733472065.830651836] [resource_manager]: Initialize hardware 'kr60' 
[control_node-1] [INFO] [1733472065.830898310] [KukaRSIHardwareInterface]: IP of client machine: 192.168.1.40:59152
[control_node-1] [INFO] [1733472065.830912456] [resource_manager]: Successful initialization of hardware 'kr60'
[control_node-1] [INFO] [1733472065.831029647] [controller_manager]: Setting component 'kr60' to 'unconfigured' state.
[control_node-1] [ERROR] [1733472065.837852346] [controller_manager]: setscheduler error
[control_node-1] [ERROR] [1733472065.838401200] [controller_manager]: Inappropriate ioctl for device
[control_node-1] [WARN] [1733472065.838416759] [controller_manager]: You can use the driver but scheduler priority was not set
[control_node-1] [INFO] [1733472066.173008403] [controller_manager]: Loading controller 'joint_trajectory_controller'
[control_node-1] [WARN] [1733472066.197555693] [joint_trajectory_controller]: [Deprecated]: "allow_nonzero_velocity_at_trajectory_end" is set to true. The default behavior will change to false.
[control_node-1] [INFO] [1733472066.204516312] [controller_manager]: Loading controller 'joint_state_broadcaster'
[spawner-5] [INFO] [1733472066.232042788] [spawner_joint_trajectory_controller]: Loaded joint_trajectory_controller
[spawner-4] [INFO] [1733472066.250684401] [spawner_joint_state_broadcaster]: Loaded joint_state_broadcaster
[control_node-1] [INFO] [1733472066.253716987] [controller_manager]: Configuring controller 'joint_state_broadcaster'
[control_node-1] [INFO] [1733472066.253857682] [joint_state_broadcaster]: 'joints' or 'interfaces' parameter is empty. All available state interfaces will be published
[control_node-1] [INFO] [1733472066.318889782] [controller_manager]: Configuring controller 'joint_trajectory_controller'
[control_node-1] [INFO] [1733472066.319119785] [joint_trajectory_controller]: No specific joint names are used for command interfaces. Using 'joints' parameter.
[control_node-1] [INFO] [1733472066.319139813] [joint_trajectory_controller]: Command interfaces are [position] and state interfaces are [position].
[control_node-1] [INFO] [1733472066.319157296] [joint_trajectory_controller]: Using 'splines' interpolation method.
[control_node-1] [INFO] [1733472066.320942077] [joint_trajectory_controller]: Controller state will be published at 50.00 Hz.
[control_node-1] [INFO] [1733472066.324113099] [joint_trajectory_controller]: Action status changes will be monitored at 20.00 Hz.
[INFO] [spawner-4]: process has finished cleanly [pid 112473]
[INFO] [spawner-5]: process has finished cleanly [pid 112475]
[control_node-1] [INFO] [1733472075.906756278] [resource_manager]: 'configure' hardware 'kr60' 
[control_node-1] [INFO] [1733472075.906792245] [resource_manager]: Successful 'configure' of hardware 'kr60'
[control_node-1] [INFO] [1733472078.891386886] [resource_manager]: 'activate' hardware 'kr60' 
[control_node-1] [INFO] [1733472078.891452199] [UDPServer]: 192.168.1.40: 59152
[control_node-1] [INFO] [1733472078.891524646] [KukaRSIHardwareInterface]: Connecting to robot . . .
[control_node-1] [INFO] [1733472082.145605808] [KukaRSIHardwareInterface]: Got data from robot
[control_node-1] [INFO] [1733472082.146177986] [KukaRSIHardwareInterface]: System Successfully started!
[control_node-1] [INFO] [1733472082.146204035] [resource_manager]: Successful 'activate' of hardware 'kr60'
[control_node-1] [INFO] [1733472082.147018644] [controller_manager]: Switch controller timeout is set to 0, using default 1s!
[robot_manager_node-2] [INFO] [1733472082.150326699] [robot_manager]: Successfully activated controllers
```

**Comment by Svastits** [comment]
If activation of the hardware is successful, controlling the robot should be possible.
You can try the following to verify where the issue lies:
- `ros2 run rqt_joint_trajectory_controller rqt_joint_trajectory_controller`, set the velocity rate to low and try to move a joint -> motion can be quite jerky
- try the same setup with `use_fake_hardware:= true` for the launch file

If robot moves in the first case, something is misconfigured for the launch_trajectory file, if it moves in the mock setup, than the issue might be with the hardware setup

**Comment by liudedong1130** [comment]
Thank you for your reply. Unfortunately, `ros2 run rqt_joint_trajectory_controller rqt_joint_trajectory_controller` still cannot control the robot to move, but `use_fake_hardware:= true` can. 
Can you tell me some key settings about kuka robot? I want to confirm where the problem with my hardware settings is. 
Below are the details of my robot network configuration. Can you help me check it?
![04f42d836cd35f3710337a9b7d2386d](https://github.com/user-attachments/assets/acd8efc7-e107-426e-8d17-3d97e7d7ea4e)
![53f7c81ec30c4ff49995a1073cbcfce](https://github.com/user-attachments/assets/d990ab5d-120d-45a5-90f9-7d5321478ce9)
![67c08c9fa3583c4efd643a6a88f6a61](https://github.com/user-attachments/assets/59e40336-89f6-4021-bab4-c9f1c080ac7b)
![78b59eba2201d5b534fec5354e18c0a](https://github.com/user-attachments/assets/301610ad-7205-490b-a5f9-74c7968db59e)
![637e4c242cebbe1608a3e9e23b1e6e1](https://github.com/user-attachments/assets/ca149ec5-f1e6-4e6c-8b1c-81e32a69da8a)
![d24f233ada73c899b5d77a05d55c943](https://github.com/user-attachments/assets/36b62657-e255-4862-a769-1615b9bbdce6)

and ros_rsi.src. Are the four states above correct? "S", "I", "R", "T1"?
![a1d08ce7e41df6397bf247e97c7dd56](https://github.com/user-attachments/assets/922d0d9f-215f-4493-8c25-83aaba64ce7a)

**Comment by Svastits** [comment]
the IP configuration seems valid for me and it seems you continually get packages from the robot controller, otherwise the client would raise a timeout. 
Looking at the smartHMI I can see 2 things:
- robot interpreter is red, in this case the robot cannot move. Are you continually pressing the enabling switch? (In T1 that is necessary, but you can also try it out in AUT)
- there are 4 status messages, can you check whether they can be connected to the issue?

**Comment by liudedong1130** [comment]
Thank you for your reply. I have found the problem. There is nothing wrong with my settings and program. The problem is that when executing ros_rsi.src in the teach pad, the play button should be held down always at the ros_movecorr() function. But I didn't do that.

**Comment by Svastits** [comment]
yes, I forgot that, play button is also necessary in T1, but not in AUT :)
