### ISSUE TITLE
[QUESTION] About IiQKA Iisy connection

### ISSUE THREAD

**Issue by guisoares9** [kroshu/kuka_drivers#206]
I noted that this repository is able to communicate with Iisy using the ExternalControl package. Do you guys remember when this package was released? Also, do you guys have a small description of what is possible to do with this package?

Asking because when we bought two robots, Kuka told us was that external communication trough sockets was not possible at that time.

**Comment by Svastits** [comment]
In short, the toolbox enables realtime monitoring or control of the iisy robots, joint-specific control modes (joint position, joint impedance and joint torque) are supported. The toolbox was released together with iiQKA 1.2 (I think  at the end of 2023 or beginning 2024), but it is not available through the used channels, you have to specifically request it from customer support
