### ISSUE TITLE
Adapt to conventions

### ISSUE THREAD

**Issue by Svastits** [kroshu/kuka_drivers#69]

**Comment by Groebehavn** [comment]
kuka_[RobotOS_name]_[RT_Tech_Name]_driver.
E.g.: kuka_kss_rsi_driver

**Comment by Groebehavn** [comment]
Inside src:
hw_interface.cpp
control_node.cpp

**Comment by Groebehavn** [comment]
Clean-up Sunrise driver as it is confusing :)

**Comment by Groebehavn** [comment]
Please provide thorough README.

**Comment by Svastits** [comment]
kuka_sunrise_interfaces -> kuka_sunrise_msgs

**Comment by Svastits** [comment]
the control_nodes for the 3 OS types could be combined somehow, as they have the same function

**Comment by Svastits** [comment]
create metapackage

**Comment by gavanderhoorn** [comment]
> kuka_sunrise_interfaces -> kuka_sunrise_msgs

just noticed this one.

`_msgs` is the ROS 1 convention.

`_interfaces` is ROS 2.

The rationale being that `_msgs` packages typically also contain definitions for `.srv` and `.action` (and with ROS 2, sometimes even `.idl` directly), and just using the `_msgs` suffix doesn't convey that fact.

Hence `_interfaces` was chosen as it's more generic (even though all of those are still "messages", just messages for a different purpose).

(tbh, personally I don't like it too much, as it's confusing for anyone with a background in programming languages which actually have an *interfaces* concept, but I understand why the name was chosen)

**Comment by Svastits** [comment]
rename RobotState msg to FRIState

**Comment by Svastits** [comment]
visibility macros should be used for all hardware interfaces

**Comment by Svastits** [comment]
Renamings done, opening new issue for proper documentation
